apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f db.yaml
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: db
    kompose.service.type: LoadBalancer
  name: db
spec:
  type: NodePort
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
      protocol: TCP
      nodePort: 30432
