elasticsearchHosts: "http://elasticsearch-master:9200"
elasticsearchCertificateSecret: ""
elasticsearchCertificateAuthoritiesFile: ""
elasticsearchCredentialSecret: ""

replicas: 1

protocol: http
httpPort: 5601
imagePullPolicy: "IfNotPresent"


kibanaConfig:
  kibana.yml: |
    server.ssl:
      enabled: "false"


resources:
  requests:
    cpu: "55m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "2Gi"
